### PR TITLE
Remove nagl nbs from skipped notebooks

### PR DESCRIPTION
**Pull request by lilyminium**
Opening this PR to see if the notebook rendering has been fixed. Related to https://github.com/openforcefield/openff-nagl/issues/92

### CODE REVIEW

**Comment by Yoshanuikabundi** [comment]
The updated notebooks should need to be in a release on Conda Forge with a tag on GitHub before the cookbook can pick them up

**Comment by lilyminium** [comment]
Ah, thanks -- I just made a release with the docs fixes and am adding it to conda now, so hopefully it'll be live by tomorrow.

**Comment by lilyminium** [comment]
Ah... my examples CI is run with OpenEye, which might be why it works in NAGL and not here.

Would you consider adding OpenEye to the examples environment @Yoshanuikabundi or should I try to change examples to find a molecule that reliably works with AmberTools?

**Comment by lilyminium** [comment]
Although it looks like it's failing to generate charges for methane?!

```
 ValueError: No registered toolkits can provide the capability "assign_partial_charges" for args "()" and kwargs "{'molecule': Molecule with name '' and SMILES '[H][C]([H])([H])[H]', 'partial_charge_method': 'am1-mulliken', 'use_conformers': [<Quantity([[ 6.25223582e+122 -1.86314103e+081  1.56369643e-096]
 [ 4.58367649e+225  3.07184515e+246 -1.82988079e-306]
 [-3.84059717e-237 -1.24119129e-267  9.87487490e+120]
 [-2.01772259e-030 -1.44408025e+199 -2.96194458e+131]
 [ 1.84149756e-157  3.19860209e+259 -6.10481269e+222]], 'angstrom')>], 'strict_n_conformers': False, 'normalize_partial_charges': True, '_cls': <class 'openff.toolkit.topology.molecule.Molecule'>}"
Available toolkits are: [ToolkitWrapper around The RDKit version 2023.03.3, ToolkitWrapper around AmberTools version 22.0, ToolkitWrapper around Built-in Toolkit version None]
 ToolkitWrapper around The RDKit version 2023.03.3 <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : partial_charge_method 'am1-mulliken' is not available from RDKitToolkitWrapper. Available charge methods are ['mmff94', 'gasteiger'] 
 ToolkitWrapper around AmberTools version 22.0 <class 'subprocess.CalledProcessError'> : Command '['antechamber', '-i', 'molecule.sdf', '-fi', 'sdf', '-o', 'charged.mol2', '-fo', 'mol2', '-pf', 'yes', '-dr', 'n', '-c', 'mul', '-nc', '0.0']' returned non-zero exit status 1.
 ToolkitWrapper around Built-in Toolkit version None <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : Partial charge method "am1-mulliken"" is not supported by the Built-in toolkit. Available charge methods are ['zeros', 'formal_charge']
```

**Comment by Yoshanuikabundi** [comment]
We'd really rather stick to freely available software in the examples environment - it's provided to users as the recommended way to run these notebooks and also used in Colab, and we want to make that process as smooth as possible. Sorry about that!

**Comment by lilyminium** [comment]
Makes sense -- I've removed it from my examples environment and made another release with a bug fix for RDKit.

**Review by Yoshanuikabundi — APPROVED** [review]
Awesome! Thanks for doing this so promptly!

**Pull request merged**
