### PR TITLE
Ecosystem modelling docs

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**
This PR adds some guidance for new users on how all the parts of OpenFF fit together, and how to find the software they want. The page added in this PR focuses on users who want to apply our force fields to their systems; users who want to produce their own force fields will come later.

I've started with a flowchart that has a lot of information and links, and I'm opening this in case anyone has any thoughts before I put time into writing stuff up. Any ideas on what a new user might find useful would be helpful!

Rendered: https://openff-docs--5.org.readthedocs.build/en/5/modelling.html

### CODE REVIEW

**Comment by Yoshanuikabundi** [comment]
@j-wags @xyzmjf I would love reviews on this!

**Review by j-wags — APPROVED** [review]
This is a huge improvement and I think it's mergeable in its current form. However, the following improvements could make this even easier for newcomers to understand. None are blocking, though.

* Add link SMIRNOFF spec earlier in section
* "OpenFF’s SMIRNOFF force fields are distributed in the [openff-forcefields](https://github.com/openforcefield/openff-forcefields) package (green in the [flowchart](https://openff-docs--5.org.readthedocs.build/en/5/modelling.html#modelling-flowchart))." --> Mention that folks can make their own FF package
* "In OpenFF-speak, a topology is a simulation system; a collection of molecules without any force field parameters or other model-specific information." --> I really don't like the use of the word "system" here but I see how it's hard to substitute
* "[OpenFF Interchange](https://docs.openforcefield.org/projects/interchange) is our package for producing simulation data in various formats." --> Instead of "producing", maybe "converting" or "exporting"?
* "...provide enough information to produce a topology and then apply a different force field" --> I'd clarify "SMIRNOFF force fields" here - atom typed FFs may be able to reparameterize some outputted systems as long as the atom types are stored. Maybe make `Topology` into a fixed-width font wiht a link that makes it clear we're talking about an OpenFF Topology. 
* "Once you have your MD engine input files from Interchange, you just simulate them in the usual way." --> "usual way" may be a blocker for newbies, maybe mention that each simulation engine has great tutorials that demonstrate standard simulation settings/practices
* "Sometimes, a general force field like the mainline OpenFF force fields just isn’t good enough" --> Jumps between singular and plural - it's probably grammatically correct but I have trouble reading it
* "If you refine torsion that’s" -- needs "a"
* Bespokefit section should use the words "accurate" and "quantum" early on - If I were a new user I wouldn't understand that "torsion drive" implies "quantum". 
* "And it works seamlessly with SMIRNOFF force fields; not only does it use a general SMIRNOFF force field as its starting point, it also produces a refined SMIRNOFF force field as its output, complete with automatic SMIRKS generation." --> Lots of details that might mislead a newcomer. You suggested "It uses a general SMIRNOFF force field as its starting point, and produces a refined SMIRNOFF force field as its output"
* (doesn't need to be this PR) Link to openff-discussions on top-level "Contact us"

**Comment by mattwthompson** [comment]
> "[OpenFF Interchange](https://docs.openforcefield.org/projects/interchange) is our package for producing simulation data in various formats." --> Instead of "producing", maybe "converting" or "exporting"?

Just a quick hitter on this point (I won't dig through everything unless you need a second pair of eyes) I think "transform" might work as the operative verb. I think the information content is roughly the same but it sounds cooler. Up to you.

**Comment by xyzmjf** [comment]
Comments attached as Open Document Text (.odt) and PDF formats. I did this so that I can highlight images in the draft documentation and explicitly comment on them. 

[2023April27MF_Comments_OpenFF_Docs_v1.odt](https://github.com/openforcefield/openff-docs/files/11345157/2023April27MF_Comments_OpenFF_Docs_v1.odt)

[2023April27MF_Comments_OpenFF_Docs_v1.pdf](https://github.com/openforcefield/openff-docs/files/11345160/2023April27MF_Comments_OpenFF_Docs_v1.pdf)

**Comment by mattwthompson** [comment]
A couple of subtler points:

* The block of OpenMM code produces objects in-memory; OpenMM doesn't use the filesystem as an intermediary between system preparation and running a simulation. The objects can be serialized out but any practitioner knows how to get those objects into a running simulation
* SMIRNOFF does not do "atom typing" in the sense that atom types (or bond types, etc.) are not produced, but it does do "typing" in the sense that parameters are applied to chemistry. "atom typing" is a no-no but "typing" is fine

**Comment by xyzmjf** [comment]
Again I am taking the viewpoint of a very new and inexperienced user here. I would that that to run the code snippet they need to do 2 things. [1] Save it to a file - say example1.py [2] Run this in their command line shell - python3 example1.py 
No doubt this is setting the bar very low, but that is how we aim to get new users on board.

**Comment by xyzmjf** [comment]
> SMIRNOFF does not do "atom typing" in the sense that atom types (or bond types, etc.) are not produced, 
> but it does do "typing" in the sense that parameters are applied to chemistry. 
> "atom typing" is a no-no but "typing" is fine

That is helpful thanks. My language is inexact as I am new and this is a novel paradigm for me !

**Comment by xyzmjf** [comment]
> The block of OpenMM code produces objects in-memory; OpenMM doesn't use the filesystem as an intermediary between 
> system preparation and running a simulation. The objects can be serialized out but any practitioner knows how to get those 
> objects into a running simulation

I realise that objects are produced in memory, but a new user sees no output (unless there is an error). 
Can we just add a simple energy minimization and print out something for the user?

**Comment by mattwthompson** [comment]
It's up to Josh but adding energy minimization and reporting would double the size of that cell block and go against the message of how a simulation can be prepared in just a few LOC. Perhaps the user could be dedicated to [examples](https://github.com/openforcefield/openff-toolkit/blob/main/examples/conformer_energies/conformer_energies.py) that are directed at this purpose

**Comment by Yoshanuikabundi** [comment]
Thanks for taking a look Mark and Matt! Matt I'm gonna stick with export because I want to emphasize the natural path through the flowchart more than I want to describe how much Interchange can do. Transform is a great word though and I will definitely use it elsewhere! Export always feels clumsy.

Thanks for your detailed comments Mark! I'll take them quickly one at a time before I head to bed...

> [1] Can we have an introduction paragraph – something like this.

I want readers to see the flowchart without scrolling, so I don't want to add more text to the top of this page. I'm also not expecting users to come to this page without knowing the basics of what OpenFF is - most users discovering us will go through https://docs.openforcefield.org first. However, that page could definitely use an introduction like the one you've written! I'll add a condensed version of it to that page before I merge this PR.

> [3] I’m not so happy about this RHS of the pipeline image:

I'm curious to hear more about this. From my perspective, this entire flowchart is intended to be new information for the user at this point - we haven't introduced Molecules or Topologies or certainly Interchanges at this point either. We've received a lot of feedback that BespokeFit is one of our "killer apps", so I want to make sure prospective users encounter it early on, and the orange box itself explains its function. So I'm inclined to leave this as it is, but maybe I could visually de-emphasize it somehow so that readers naturally focus on the other parts of the flowchart and don't get distracted?

> [4] It is really great to include some code for the user to run, and this is (almost) a good example.

I agree with Matt on this one - users familiar with Python will probably be more comfortable with in-memory output like what the current example has than writing out a file, for instance, which are a minor pain to work with in Python. For those users, the last three lines basically act as output (which they don't even have to run the example to see). If we just wanted file-type output, we could substitute the OpenMM lines for GROMACS or Amber or CHARMM, which all would then create files; I don't really think that adds anything (except complication for the test environment).

Users who are not familiar with Python will struggle either way - almost all of our tools really require some level of comfort with Python. The point of this code example is to emphasize how easy our tools are, not for users to necessarily copy it - even with an energy calculation a vacuum MM point energy of a drug molecule is not going to be super useful.

Having said that, if there were a one-liner to compute a point energy or something like that in OpenMM I would totally add it here - but the best I could come up with is this:

```python
from openff.toolkit import Molecule, Topology, ForceField
from openff.interchange import Interchange
import openmm

paracetamol = Molecule.from_smiles("CC(=O)NC1=CC=C(C=C1)O")
paracetamol.generate_conformers(n_conformers=1)

topology = Topology.from_molecules([paracetamol])

force_field = ForceField("openff-2.0.0.offxml")

interchange = Interchange.from_smirnoff(force_field, topology)

openmm_system = interchange.to_openmm()
openmm_topology = interchange.to_openmm_topology()
openmm_positions = interchange.positions.to_openmm()

simulation = openmm.app.simulation.Simulation(
    openmm_topology, 
    openmm_system, 
    openmm.VerletIntegrator(2.0 * openmm.unit.femtosecond),
)
simulation.context.setPositions(openmm_positions)
simulation.minimizeEnergy()
simulation.context.getState(getEnergy=True).getPotentialEnergy()
```

Which adds 9 lines to a previously 10 line example, and is mostly gobbledygook for people not familiar with OpenMM.

The point about examples generally lacking throughout the docs is well taken, and I've already started work on a centralized example page that will make this much easier (and which we'll link to from here when it becomes available). But I don't think complicating the ad for simplicity is the way to solve that problem.

> [5] Now I have a quite general point about SMIRNOFF. As I now understand it, we do not actually do ‘atom typing’ using SMIRKS patterns as SMIRKS relates to chemical reactions. We do ‘atom typing’ or chemical environment perception and
parameter assignment using SMARTS patterns – as SMARTS relates to chemical substructures.

This is exactly right and it annoys me too. SMIRKS is a superset of SMARTS, so if we use SMARTS it is technically correct to say that we also use SMIRKS. The part of SMIRKS that is used is the atom indexing - you can distinguish eg. the hydrogens in a water SMIRKS with "[H:1]O[H:2]". SMIRKS intended this to show which atoms are the same in the reactant and product, but SMIRNOFF uses this to specify which atoms actually get the parameter - this way we can use neighboring atoms to specify parameters that don't actually affect them. So, I dunno, a carbonyl carbon's LJ parameter SMIRKS might be `"C=[O:1]"` for instance, and could be distinguished from an ester `"OC=[O:1]"`.

Daylight later added this indexing to the SMILES (which SMARTS is a superset of) spec, but SMARTNOFF is not a popular vodka brand, so we're stuck with SMIRNOFF.

**Comment by Yoshanuikabundi** [comment]
Maybe one day we'll come up with a coarse grained force field and call it SMARTINI

**Comment by j-wags** [comment]
This is really great discussion - we don't often go deep into the pareto front of our choices but it's really handy to have a new set of eyes to point out things that I overlook when seeing for the thousandth time.

Given that this is intended to be the first point of contact for _all new arrivals to our ecosystem_ it is worth a lot of polishing. Ideally this will be a straightforward document that is easy for newcomers to parse, but which experts will be able to read and come away with deeper levels of meaning. That's a tall order.

That said, it's worth keeping in mind:
* @Yoshanuikabundi is product owner for openff-docs so he's free to unilaterally make any choice he wants.
* This page will continue to evolve over time, so merging this PR doesn't end these discussions, but it does get something useful in the hands of users immediately.
* Taking into consideration time zone overlaps, we can only expect a max of 4 rounds of feedback per week on this discussion. 

@xyzmjf For consideration, I tried to minimally run an openmm simulation that writes familiar files (pdb and dcd) to disk and came up with the code below. I could probably reduce the number of lines a little, but it would come at the cost of making the remaining lines look more like the "gobbledygook" mentioned above. 

One compromise could be defaulting to collapsing the "simulate" and "visualize" sections, so users have to click to expand them. Is this possible @Yoshanuikabundi? If not I support sticking with the current version and linking to an example that shows how to do a simulation. 

```python
from openff.toolkit import Molecule, Topology, ForceField
from openff.interchange import Interchange

paracetamol = Molecule.from_smiles("CC(=O)NC1=CC=C(C=C1)O")
paracetamol.generate_conformers(n_conformers=1)

topology = Topology.from_molecules([paracetamol])

force_field = ForceField("openff-2.0.0.offxml")

interchange = Interchange.from_smirnoff(force_field, topology)

openmm_system = interchange.to_openmm()
openmm_topology = interchange.to_openmm_topology()
openmm_positions = interchange.positions.to_openmm()

# Run a simulation
import openmm
import openmm.unit as openmm_unit
integrator = openmm.VerletIntegrator(1 * openmm_unit.femtoseconds)
platform = openmm.Platform.getPlatformByName("Reference")
simulation = openmm.app.Simulation(openmm_topology, openmm_system, integrator, platform)
simulation.context.setPositions(openmm_positions)
# Add a reporter to record the structure every 10 steps, and write a pdb with the basic topology for visualization
paracetamol.to_file("paracetamol.pdb", file_format="pdb")
dcd_reporter = openmm.app.DCDReporter("paracetamol.dcd", 10)
simulation.reporters.append(dcd_reporter)
simulation.context.setVelocitiesToTemperature(300 * openmm_unit.kelvin)
simulation.step(1000)

# Visualize the trajectory in a notebook (skip this if you prefer VMD)
import nglview
import mdtraj

mdt_traj = mdtraj.load("paracetamol.dcd", top="paracetamol.pdb")
w = nglview.show_mdtraj(mdt_traj)
w
```
In a notebook, the last bit pops up a simulation visualization:
> Screen Shot 2023-04-27 at 10 24 32 AM

**Comment by Yoshanuikabundi** [comment]
Had an idea about an API point that would make a full energy minimisation possible in the constraints of this page, so I've opened https://github.com/openforcefield/openff-interchange/issues/713

I've made the changes I discussed above and I'm merging this now as I really want this out there before the meeting - if there are other changes people think we should do, please raise an issue!

**Pull request merged**
