### PR TITLE
Update NAGL in examples

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**
I'm getting some very strange performance regressions locally but we'll see what happens here.

### CODE REVIEW

**Comment by Yoshanuikabundi** [comment]
That [did actually work](https://github.com/openforcefield/openff-docs/actions/runs/5467630310) it's just that the preproc action runs off this branch so the comments aren't on this branch yet - merging in `main` will make the comments appear for future regenerations.

**Comment by Yoshanuikabundi** [comment]
Hey @lilyminium - This seems to be working on main with nagl 0.2.2, but it doesn't like 0.2.3. Do you have any insight?

The error in the two runs above is in openforcefield/openff-toolkit/QCArchive_interface/QCarchive_interface.ipynb, so it could be an intermittent error from QCA, but it was reliable for dozens of test runs while I was writing the PR so I wonder if its possible something has changed in the environment.

When I run it locally the openforcefield/openff-toolkit/virtual_sites/vsite_showcase.ipynb
example times out - the time out is 600 seconds and it used to take less than 300 so I don't want to just extend the timeout without figuring out what's going on.

The diff between the outputs of `micromamba list` on the last failed run (on this branch) and the last successful run (on `main`) is:

```diff
--- Last failed run	Thu Jul  6 08:53:00 2023
+++ last successful run	Thu Jul  6 08:53:00 2023
@@ -1,4 +1,4 @@
-Last failed run
+  last successful run
   List of packages in environment: "/home/runner/micromamba/envs/openff-docs-examples"
   
     Name                           Version       Build                         Channel            
@@ -226,7 +226,7 @@
     openff-interchange             0.3.7         pyhd8ed1ab_0                  conda-forge        
     openff-interchange-base        0.3.7         pyhd8ed1ab_0                  conda-forge        
     openff-models                  0.0.5         pyh1a96a4e_0                  conda-forge        
-    openff-nagl                    0.2.3         pyhd8ed1ab_0                  conda-forge        
+    openff-nagl                    0.2.2         pyhd8ed1ab_0                  conda-forge        
     openff-toolkit                 0.14.0        pyhd8ed1ab_1                  conda-forge        
     openff-toolkit-base            0.14.0        pyhd8ed1ab_1                  conda-forge        
     openff-toolkit-examples        0.14.0        hd8ed1ab_1                    conda-forge        
@@ -251,7 +251,7 @@
     pbr                            5.11.1        pyhd8ed1ab_0                  conda-forge        
     pcre2                          10.40         hc3806b6_0                    conda-forge        
     pdbfixer                       1.9           pyh1a96a4e_0                  conda-forge        
-    perl                           5.32.1        3_hd590300_perl5              conda-forge        
+    perl                           5.32.1        2_h7f98852_perl5              conda-forge        
     pexpect                        4.8.0         pyh1a96a4e_2                  conda-forge        
     pickleshare                    0.7.5         py_1003                       conda-forge        
     pillow                         10.0.0        py310h582fbeb_0               conda-forge        
@@ -368,4 +368,3 @@
     zipp                           3.15.0        pyhd8ed1ab_0                  conda-forge        
     zlib                           1.2.13        hd590300_5                    conda-forge        
     zlib-ng                        2.0.7         h0b41bf4_0                    conda-forge        
-    zstd                           1.5.2         h3eb15da_6                    conda-forge        
```

I'll try adding zstd to the environment but I have no idea what it does

**Comment by Yoshanuikabundi** [comment]
This comment should not trigger a dispatch

**Comment by lilyminium** [comment]
So the error is in *other* notebooks that don't use NAGL? That's surprising :/ there should be very little difference between v0.2.2 and v0.2.3 -- the only updates are in docs and metadata:
https://github.com/openforcefield/openff-nagl/compare/v0.2.2...v0.2.3

**Comment by Yoshanuikabundi** [comment]
> So the error is in other notebooks that don't use NAGL?

Yep!

> That's surprising :/

This feels like a huge understatement :laughing: 

Jeff reckons the QCA time outs are spooky action at a distance from changes QCA serverside, so maybe its just my computer acting up. 

The timeout is extremely, worryingly reproducible - every time I recreate an environment with NAGL 0.2.2 it works, and with 0.2.3 it times out. Here's my latest conda environment diff:

```diff
--- git checkout main	Thu Jul  6 09:49:08 2023
+++ git checkout update-nagl	Thu Jul  6 09:49:08 2023
@@ -1,4 +1,4 @@
-git checkout main
+git checkout update-nagl
 List of packages in environment: "/home/joshmitchell/Documents/openff/openff-docs/.soap/examples"
 
   Name                           Version       Build                         Channel            
@@ -232,7 +232,7 @@
   openff-interchange             0.3.7         pyhd8ed1ab_0                  conda-forge        
   openff-interchange-base        0.3.7         pyhd8ed1ab_0                  conda-forge        
   openff-models                  0.0.5         pyh1a96a4e_0                  conda-forge        
-  openff-nagl                    0.2.2         pyhd8ed1ab_0                  conda-forge        
+  openff-nagl                    0.2.3         pyhd8ed1ab_0                  conda-forge        
   openff-toolkit                 0.14.0        pyhd8ed1ab_1                  conda-forge        
   openff-toolkit-base            0.14.0        pyhd8ed1ab_1                  conda-forge        
   openff-toolkit-examples        0.14.0        hd8ed1ab_1                    conda-forge        
@@ -374,4 +374,4 @@
   zipp                           3.15.0        pyhd8ed1ab_0                  conda-forge        
   zlib                           1.2.13        hd590300_5                    conda-forge        
   zlib-ng                        2.0.7         h0b41bf4_0                    conda-forge        
-  zstd                           1.5.2         h3eb15da_6                    conda-forge    
+  zstd                           1.5.2         h3eb15da_6                    conda-forge        
```

I'll see what happens if I run the notebook in Jupyter Lab...

**Comment by Yoshanuikabundi** [comment]
The vsites notebook works on Jupyter Lab. Jeff thinks its a thread safety thing (he's probably right). I don't understand why it happens so consistently but it's possible. I'm going to try running it a few more times in this PR and see what happens.

**Comment by lilyminium** [comment]
I think some of the failure may be due to failing to copy directories -- although this is a new addition in 0.3.x -- https://github.com/openforcefield/openff-docs/actions/runs/5851460527/job/15862259538#step:7:21

**Comment by Yoshanuikabundi** [comment]
Superseded by #42

**Pull request closed without merging**
