### PR TITLE
Update Interchange to 0.4.0

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**

### CODE REVIEW

**Comment by Yoshanuikabundi** [comment]
@j-wags @mattwthompson The above notebook failure has already been fixed in the Toolkit, so we need to either 

1. Make a new Toolkit release
2. Wait to merge this and leave the examples on Interchange 0.3.x, or 
3. Merge this and let the failing example continue to fail until a new Toolkit release comes out - the notebook will not be displayed on the examples page, but everything else will be fine.

**Comment by mattwthompson** [comment]
I think Jeff is in the process of rolling out (1)

**Comment by j-wags** [comment]
I quietly made the Toolkit 0.16.6 release last Friday which updates the examples, so hopefully rerunning CI will get these going again.

**Pull request merged**
