### PR TITLE
Use less-likely-to-be-buggy Interchange

### PR DESCRIPTION
**Pull request by mattwthompson**
While checking workshop materials, I noticed the examples are rendered with an outdated constraint

### CODE REVIEW

**Review by j-wags — COMMENTED** [review]
I'm generally in favor but just don't want to update this right before our first workshop (almost certainly won't make a difference, but no need to take the risk!).

**Review by j-wags — APPROVED** [review]
Thanks @mattwthompson !

**Comment by j-wags** [comment]
Let's make sure this actually builds before merging - I should have just triggered a third CI run

**Comment by mattwthompson** [comment]
Trying to independently fix the automation in #38

**Comment by mattwthompson** [comment]
The automation is still broken, but the charge caching bug needs to be removed from history so I'm making the decision to just merge this as-is

**Pull request merged**
